FROM node:21-alpine3.19

WORKDIR /app

COPY package.json tsconfig.json .npmrc ./

COPY src ./src
COPY tools ./tools

RUN ls -a

RUN npm install && npm install -g nodemon

EXPOSE 4001

CMD [ "npm", "run", "dev" ]